INSERT INTO <SCH><THIP>PARAM_PSN (ID_PROGRESSIVO, ID_FUNZIONE, ID_PARAMETRO, ID_AZIENDA, DESCRIZIONE, DESCR_RIDOTTA, R_RIFER_ATTRIB, VALORE_PARAM, STATO, R_UTENTE_CRZ, R_UTENTE_AGG, NOTA, AREA, NUMERO_FIX) VALUES (<NUM><PARAM_PSN>, 'pers.base.articolo.IdentificatoreManici', 'IdMacroFamiglia', null, 'Codice macrofamiglia Manici', 'Codice macrofam', 'IdMacroFamiglia', 'M01', 'V', <USER>, <USER> , null, 'D' , null);
INSERT INTO <SCH><THIP>PARAM_PSN_L (ID_PROGRESSIVO, ID_LINGUA, DESCRIZIONE, DESCR_RIDOTTA) VALUES (<LAST_NUM><PARAM_PSN>,'it', 'Codice macrofamiglia Manici', 'Codice macrofam');


