# Class path : com.thera.thermfw.util.Replacement
# Class name : REPLACEMENT
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.produzione.raccoltaDati.web.RilevDatiPrdTSFormActionAdapter', 'it.tonini.thip.produzione.raccoltaDati.web.YRilevDatiPrdTSFormActionAdapter', '0', 'N');
    INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it.thera.thip.produzione.raccoltaDati.web.AzioneDichiarazioneTS', 'it.tonini.thip.produzione.raccoltaDati.web.YAzioneDichiarazioneTS', '0', 'N');
  	INSERT INTO <SCH>REPLACEMENT (ORIGINAL_NAME,REPLACING_NAME,TYPE,DISABLED) VALUES ('it/thera/thip/produzione/raccoltaDati/DichiarazioneMonitor.js', 'it/tonini/thip/produzione/raccoltaDati/YDichiarazioneMonitor.js', '2', 'N');